//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACI_Chip_OrdenAtencion
    {
        public int idChipOrdenAtencion { get; set; }
        public int idOrdenAtencion { get; set; }
        public int idChip { get; set; }
    
        public virtual ACI_Chip ACI_Chip { get; set; }
        public virtual ACI_OrdenAtencion ACI_OrdenAtencion { get; set; }
    }
}
