//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CE_Estado
    {
        public CE_Estado()
        {
            this.GPC_Solicitud = new HashSet<GPC_Solicitud>();
        }
    
        public int codigo_estado { get; set; }
        public string descripcion_estado { get; set; }
    
        public virtual ICollection<GPC_Solicitud> GPC_Solicitud { get; set; }
    }
}
