//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cartilla_Atencion = new HashSet<Cartilla_Atencion>();
            this.Comprobante_Pago = new HashSet<Comprobante_Pago>();
        }
    
        public int id_cliente { get; set; }
        public string dni { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string nombres { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public string telefono_casa { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public virtual ICollection<Comprobante_Pago> Comprobante_Pago { get; set; }
    }
}
