//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Examen
    {
        public int id { get; set; }
        public int id_comprobante { get; set; }
        public int id_tipo_examen { get; set; }
    
        public virtual Comprobante_Pago Comprobante_Pago { get; set; }
        public virtual Examen Examen { get; set; }
    }
}
