//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Atencion
    {
        public int id_detalle { get; set; }
        public int id_cartilla_atencion { get; set; }
        public int id_tipo_examen { get; set; }
        public Nullable<int> CodigoEmpleado { get; set; }
        public string especificacion_examen { get; set; }
        public string estado_examen_atencion { get; set; }
        public Nullable<int> id_equipo { get; set; }
    
        public virtual Cartilla_Atencion Cartilla_Atencion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Equipo_Sede Equipo_Sede { get; set; }
        public virtual Examen Examen { get; set; }
    }
}
