//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Cartilla_Atencion = new HashSet<Cartilla_Atencion>();
            this.Detalle_Atencion = new HashSet<Detalle_Atencion>();
            this.Solicitud = new HashSet<Solicitud>();
            this.Solicitud1 = new HashSet<Solicitud>();
            this.GPC_Solicitud = new HashSet<GPC_Solicitud>();
        }
    
        public int CodigoEmpleado { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string Correo { get; set; }
        public int CodigoArea { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public bool EstadoRegistro { get; set; }
        public string dni { get; set; }
        public string especialidad { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string telefono_casa { get; set; }
        public string celular { get; set; }
        public string cargo { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public Nullable<int> id_sede { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public virtual ICollection<Detalle_Atencion> Detalle_Atencion { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual ICollection<Solicitud> Solicitud1 { get; set; }
        public virtual ICollection<GPC_Solicitud> GPC_Solicitud { get; set; }
    }
}
