//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoSolicitud
    {
        public EstadoSolicitud()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int CodigoEstadoSolicitud { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
