//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPC_DetalleDeSolicitud
    {
        public int item { get; set; }
        public Nullable<double> cantidad_solicitada { get; set; }
        public Nullable<double> cantidad_aprobada { get; set; }
        public Nullable<double> cantidad_atendida { get; set; }
        public Nullable<int> codigo_recurso { get; set; }
        public int numero_solicitud { get; set; }
    
        public virtual GPC_Recurso GPC_Recurso { get; set; }
        public virtual GPC_Solicitud GPC_Solicitud { get; set; }
    }
}
