//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadesxFichaMantenimiento
    {
        public int CodigoActividadxFichaMantenimiento { get; set; }
        public string Descripcion { get; set; }
        public int CodigoFichaMantenimiento { get; set; }
        public int CodigoActividad { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual FichaMantenimiento FichaMantenimiento { get; set; }
    }
}
