//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cartilla_Atencion = new HashSet<Cartilla_Atencion>();
            this.Paciente = new HashSet<Paciente>();
            this.Paciente1 = new HashSet<Paciente>();
            this.Comprobante_Pago = new HashSet<Comprobante_Pago>();
        }
    
        public int id_cliente { get; set; }
        public string dni { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string nombres { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public string telefono_casa { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual ICollection<Paciente> Paciente1 { get; set; }
        public virtual ICollection<Comprobante_Pago> Comprobante_Pago { get; set; }
    }
}
