//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Pago
    {
        public Comprobante_Pago()
        {
            this.Comprobante_Examen = new HashSet<Comprobante_Examen>();
        }
    
        public int id_comprobante { get; set; }
        public int id_cliente { get; set; }
        public int id_paciente { get; set; }
        public string numero_comprobante { get; set; }
        public Nullable<decimal> monto_total { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tipo_comprobante { get; set; }
        public string forma_pago { get; set; }
        public string estado_comprobante { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Comprobante_Examen> Comprobante_Examen { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
