//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Cartilla_Atencion = new HashSet<Cartilla_Atencion>();
            this.Detalle_Atencion = new HashSet<Detalle_Atencion>();
            this.Solicitud = new HashSet<GPC_Solicitud>();
            this.Solicitud1 = new HashSet<GPC_Solicitud>();
        }
    
        public int CodigoEmpleado { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string Correo { get; set; }
        public int CodigoArea { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public bool EstadoRegistro { get; set; }
        public string dni { get; set; }
        public string especialidad { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string telefono_casa { get; set; }
        public string celular { get; set; }
        public string cargo { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public Nullable<int> id_sede { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public virtual ICollection<Detalle_Atencion> Detalle_Atencion { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual ICollection<GPC_Solicitud> Solicitud { get; set; }
        public virtual ICollection<GPC_Solicitud> Solicitud1 { get; set; }
    }
}
