//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public Examen()
        {
            this.Comprobante_Examen = new HashSet<Comprobante_Examen>();
            this.Detalle_Atencion = new HashSet<Detalle_Atencion>();
        }
    
        public int id_tipo_examen { get; set; }
        public string tipo_examen { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual ICollection<Comprobante_Examen> Comprobante_Examen { get; set; }
        public virtual ICollection<Detalle_Atencion> Detalle_Atencion { get; set; }
    }
}
