//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public Tecnico()
        {
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
        }
    
        public int CodigoEmpleado { get; set; }
        public int CodigoTecnico { get; set; }
        public int CodigoEspecialidad { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaHoraActualizacion { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
    }
}
